replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

proxy:
  location: |-
    proxy_pass http://backend;
  upstreamBackend: |-
    server app:80;

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  supplementalGroups: []
  sysctls: []

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 101
  runAsNonRoot: true
  runAsUser: 101
  seLinuxOptions: {}
  seccompProfile:
    type: RuntimeDefault

service:
  type: ClusterIP
  port: 80
  containerPort: 8080

resources:
  requests:
    cpu: 5m
    #memory: 48Mi

livenessProbe:
  readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 10
  httpGet:
    port: http
    path: /readyw
readinessProbe:
  readinessProbe:
  initialDelaySeconds: 0
  periodSeconds: 1
  failureThreshold: 10
  httpGet:
    port: http
    path: /readyw

volumes:
  tmp:
    emptyDir: {}

extraVolumes: []
extraVolumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
